// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkfcytxrfushqapackut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZmN5dHhyZnVzaHFhcGFja3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDc0OTYsImV4cCI6MjA2NjQyMzQ5Nn0.QzLMGx9Pp0gnNULcbGviMxNTfk9kD9apP-BoGoMtlV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);